SHELL := /bin/bash
#REPOS="rosjava_build_tools" "rosjava_bootstrap" "genjava" "rosjava_test_msgs" "rosjava_messages" "rosjava_core" "rosjava_extras" "zeroconf_jmdns_suite"
REPOS="rosjava_build_tools"
SRC_GIT=https://github.com/rosjava
REL_GIT=https://github.com/rosjava-release
TRACK=indigo
SOURCE_BRANCH=indigo

include ../Makefile

