SHELL := /bin/bash
#REPOS="rosjava_build_tools" "rosjava_bootstrap" "rosjava_messages"
REPOS="rosjava_build_tools" "rosjava_bootstrap"
SRC_GIT=https://github.com/rosjava
REL_GIT=https://github.com/rosjava-release
TRACK=hydro

include ../Makefile

