SHELL := /bin/bash
#REPOS="world_canvas_msgs" "world_canvas_libs" "world_canvas"
REPOS="world_canvas_msgs"
SRC_GIT=https://github.com/yujinrobot
REL_GIT=https://github.com/yujinrobot-release
TRACK=kinetic
SOURCE_BRANCH=kinetic

include ../Makefile

