SHELL := /bin/bash
#REPOS="kobuki_msgs" "kobuki" "yujin_ocs"
REPOS="rosbridge_suite"
SRC_GIT=https://github.com/RobotWebTools
REL_GIT=https://github.com/RobotWebTools-release

include ../Makefile

















































