SHELL := /bin/bash
#REPOS="yocs_msgs" "yocs"
REPOS="yocs_msgs"
SRC_GIT=https://github.com/yujinrobot
REL_GIT=https://github.com/yujinrobot-release
TRACK=kinetic
SOURCE_BRANCH=kinetic

include ../Makefile

