SHELL := /bin/bash
#REPOS="yocs_msgs" "yujin_ocs"
REPOS="yujin_ocs"
SRC_GIT=https://github.com/yujinrobot
REL_GIT=https://github.com/yujinrobot-release
TRACK=kinetic
SOURCE_BRANCH=kinetic

include ../Makefile

