SHELL := /bin/bash
#REPOS="kobuki_msgs" "kobuki_core" "kobuki" "yujin_ocs"
REPOS="kobuki_core"
SRC_GIT=https://github.com/yujinrobot
REL_GIT=https://github.com/yujinrobot-release
TRACK=kinetic
SOURCE_BRANCH=kinetic

include ../Makefile

