SHELL := /bin/bash
#REPOS="rocon_msgs" "rocon_multimaster" "rocon_app_platform" "rocon_concert" "rocon_tutorials" "rocon_rqt_plugins"
REPOS="yaml_cpp_0_3"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=indigo
SOURCE_BRANCH=indigo

include ../Makefile

