SHELL := /bin/bash
REPOS="opencv2"
SRC_GIT=https://github.com/stonier
REL_GIT=https://github.com/yujinrobot-release
TRACK=indigo
SOURCE_BRANCH=indigo

#include ../Makefile

bloom:
	bloom-release --track ${TRACK} --rosdistro ${TRACK} opencv2

