SHELL := /bin/bash
REPOS="sophus_ros_toolkit"
SRC_GIT=https://github.com/yujinrobot
REL_GIT=https://github.com/yujinrobot-release
TRACK=indigo
SOURCE_BRANCH=release/0.1-indigo-kinetic

include ../Makefile

