SHELL := /bin/bash
#REPOS="turtlebot" "rosjava_bootstrap" "rosjava_messages"
REPOS="turtlebot_apps"
SRC_GIT=https://github.com/turtlebot
REL_GIT=https://github.com/turtlebot-release
TRACK=hydro

include ../Makefile

