SHELL := /bin/bash
#REPOS="turtlebot" "rosjava_bootstrap" "rosjava_messages"
REPOS="turtlebot"
SRC_GIT=https://github.com/turtlebot
REL_GIT=https://github.com/turtlebot-release
TRACK=hydro
SOURCE_BRANCH=hydro

include ../Makefile

